#Descarga de Ubuntu 20.04
FROM ubuntu:20.04
#Etiquetas sobre el autor
LABEL description = "Contenedor para trabajar un modelo de regresion"
LABEL mainteiner = "Fatima Yatcin PC"
LABEL version = "0.1"
#Actualizar e instalar python
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y python3
RUN apt-get install -y python3-pip
RUN apt-get clean

#Instalar paquetes de requirements.txt

ENV requirements /home/requirements.txt

COPY requirements.txt ${requirements}

RUN pip3 install -r /home/requirements.txt